import { ThemePalette } from "../palette";

export const LIGHT_STUDIO_THEME: ThemePalette = {
    id: 'light-studio',
    name: 'Light Studio Pro',
    ui: {
        bgApp: '#e2e8f0',
        bgHeader: 'rgba(226, 232, 240, 0.95)',
        bgSurface: '#edf2f7',
        bgSurfaceElevated: '#e2e8f0',
        borderSubtle: '#cbd5e1',
        borderMuted: '#94a3b8',
        textPrimary: '#1e293b',
        textSecondary: '#475569',
        textMuted: '#64748b',
        accentPrimary: '#1a49b0',
        accentPrimaryHover: '#1d4ed8',
        accentPrimaryGlow: 'rgba(37, 99, 235, 0.2)',
    },
    graph: {
        background: '#e2e8f0',
        grid: 'rgba(148, 163, 184, 0.35)',
        selectionOutline: '#3b82f6',
        tempEdgeLine: '#2563eb',
        edges: {
            idle: '#98a7b3',
            active: '#d97706',
            traversed: '#94a3b8',
            path: '#0284c7',
        },
        nodes: {
            idle: {
                fillGradientStart: '#f1f5f9',
                fillGradientEnd: '#e2e8f0',
                stroke: '#94a3b8',
                strokeHover: '#c5cdd9',
                text: '#1e293b',
            },
            start: {
                fillGradientStart: '#10b981',
                fillGradientEnd: '#059669',
                stroke: '#047857',
                glow: 'rgba(16, 185, 129, 0.3)',
                badgeBg: '#059669',
                text: '#ffffff',
            },
            goal: {
                fillGradientStart: '#f43f5e',
                fillGradientEnd: '#e11d48',
                stroke: '#be123c',
                glow: 'rgba(244, 63, 94, 0.3)',
                badgeBg: '#e11d48',
                text: '#ffffff',
            },
            current: {
                fillGradientStart: '#f59e0b',
                fillGradientEnd: '#d97706',
                stroke: '#b45309',
                glow: 'rgba(245, 158, 11, 0.35)',
                text: '#ffffff',
            },
            inQueue: {
                fillGradientStart: '#0284c7',
                fillGradientEnd: '#0369a1',
                stroke: '#075985',
                glow: 'rgba(2, 132, 199, 0.25)',
                badgeBg: '#0284c7',
                text: '#ffffff',
            },
            visited: {
                fillGradientStart: '#cbd5e1',
                fillGradientEnd: '#94a3b8',
                stroke: '#64748b',
                badgeBg: '#64748b',
                text: '#1e293b',
            },
            path: {
                fillGradientStart: '#38bdf8',
                fillGradientEnd: '#0284c7',
                stroke: '#0369a1',
                glow: 'rgba(56, 189, 248, 0.45)',
                text: '#ffffff',
            },
        },
    },
};
